#1 Add initial project
itell-solutions/django_postgres_backup pull request #2
Opened 2022-09-08 07:41 UTC by davidmarogy

See #1

2022-10-04 10:05 UTC, roskakori requested changes

2022-10-04 10:05 UTC, roskakori commented on .github/workflows/build.yaml
> +        image: postgres:12 # Same version as Ubuntu 20 LTS.
Bump to 14 and Ubuntu 22 LTS

2022-10-04 10:05 UTC, roskakori commented on README.md
> +
Apply fixed description from GitHub project:
> Django managed commands to backup and restore PostgreSQL databases with multiple generations

2022-10-04 10:05 UTC, roskakori commented on README.md
> +
Also make this a proper readme with complete documentation, examples, badges etc

2022-10-04 10:05 UTC, roskakori commented on django_postgres_backup/common.py
> +    subprocess.check_call(command, cwd=BASE_DIR, shell=shell)
What is the point of `cwd=BASE_DIR`? Wouldn't it be more transparent if the application used the current directory of the user?

2022-10-04 10:05 UTC, roskakori commented on django_postgres_backup/common.py
> +        command = f"{sudo_command} bzip2 -d -c {file} -k | {command}"
As `{file}` can be specified by user, arbitraty commands can be injected.

Shell-escape file: [shlex.quote](http://docs.python.org/dev/library/shlex.html#shlex.quote).

2022-10-04 10:05 UTC, roskakori commented on django_postgres_backup/common.py
> +        command = f"{sudo_command} {command} {file}"
Shell-escape `{file}`

2022-10-04 10:05 UTC, roskakori commented on django_postgres_backup/common.py
> +BACKUP_PATH = BASE_DIR / "backup"
Is this the `DEFAULT_BACKUP_PATH`?

2022-10-04 10:05 UTC, roskakori commented on django_postgres_backup/common.py
> +def backup_file(
Maybe:
```python
def backup_path(base_dir: str, database_name: str, file_name: Optional[str] = None) -> str:
    ...
```

2022-10-04 10:05 UTC, roskakori commented on django_postgres_backup/common.py
> +    additional_commands = ""
Use list:
```python
    additional_commands = []
    if clean:
        additional_commands.append("--clean")
    if if_exists:
        additional_commands.append("--if-exists")

    command = (
        f"PGPASSWORD={DATABASE_PASSWORD} pg_restore --host={DATABASE_HOST} --port={DATABASE_PORT} "
        f"--username={username} --dbname={database_name} --format={database_format} "
        f"{additional_commands.join(' '}"
    )
```

```

2022-10-04 10:05 UTC, roskakori commented on django_postgres_backup/management/commands/postgres_backup.py
> +        parser.add_argument(
`--path` does not make it clear if this is a file or directory. 

Maybe use `--backup-folder` or `--backup-dir` and `-b`?

(Same with other managed command)

2022-10-04 10:05 UTC, roskakori commented on django_postgres_backup/management/commands/postgres_backup.py
> +        run(["mkdir", "-p", "backup"])
Use [os.makedirs(..., exist_ok=True)](https://docs.python.org/3/library/os.html?highlight=makedir#os.makedirs), which is OS independent and much faster than a shell command.

2022-10-04 10:05 UTC, roskakori commented on django_postgres_backup/management/commands/postgres_backup.py
> +        run(["mkdir", "-p", "backup"])
Shouldn't this refer to `path` instead of `"backup"`?

2022-10-04 10:05 UTC, roskakori commented on django_postgres_backup/management/commands/postgres_restore.py
> +    help = "Download bootstrap, build template css and copy bootstrap.bundle.min.js"
Fix description.

2022-10-04 10:05 UTC, roskakori commented on django_postgres_backup/management/commands/postgres_backup.py
> +    help = "Download bootstrap, build template css and copy bootstrap.bundle.min.js"
Fix description.

2022-10-04 10:05 UTC, roskakori commented on django_postgres_backup/management/commands/postgres_backup.py
> +        parser.add_argument("--format", "-fo", metavar="FORMAT", default=DEFAULT_DATABASE_BACKUP_FORMAT)
Add help to describe that this accepts the same values as the external postgres command.

2022-10-04 10:05 UTC, roskakori commented on django_postgres_backup/management/commands/postgres_backup.py
> +        parser.add_argument("--file", "-f", metavar="FILENAME", default=DATABASE_NAME)
Is this a full file path or just a name? Maybe use `--name` instead?

2022-10-04 10:05 UTC, roskakori commented on django_postgres_backup/management/commands/postgres_backup.py
> +        parser.add_argument("--generation", "-g", metavar="GENERATION", default=POSTGRES_BACKUP_GENERATIONS, type=int)
Plural: `--generations`

Also add `help="..."`

2022-10-04 10:05 UTC, roskakori commented on django_postgres_backup/management/commands/postgres_restore.py
> +    def add_arguments(self, parser):
For some of the options below consider adding `help="..."` similar to above.

2022-10-04 10:05 UTC, roskakori commented on django_postgres_backup/tests/test_commands.py
> +TEST_CREATE_TABLE_CARS_SQL = "create table cars (id SERIAL PRIMARY KEY , name VARCHAR(255) NOT NULL);"
Use lower case SQL consistently.

2022-10-04 10:05 UTC, roskakori commented on docker-compose.yaml
> +      POSTGRES_PASSWORD: "hid_d3n."
Use a more generic test password like "not-secret".

2022-10-04 10:05 UTC, roskakori commented on example_app/admin.py
> +# Register your models here.
Remove comment.

2022-10-04 10:05 UTC, roskakori commented on example_app/models.py
> +# Create your models here.
Remove comment.

2022-10-04 10:05 UTC, roskakori commented on example_app/views.py
> +# Create your views here.
Remove file.

2022-10-04 10:05 UTC, roskakori commented on scripts/reset_local_database.sh
> +# TODO: After migrations are under version control, remove this.
Is this still a TODO?

2022-10-04 10:05 UTC, roskakori commented on scripts/reset_local_database.sh
> +# TODO: python manage.py makedemo
Still a TODO?

2022-10-06 07:46 UTC, davidmarogy commented on .github/workflows/build.yaml
> +        image: postgres:12 # Same version as Ubuntu 20 LTS.
Done

2022-10-06 09:00 UTC, davidmarogy commented on django_postgres_backup/common.py
> +    subprocess.check_call(command, cwd=BASE_DIR, shell=shell)
Removed cwd. BASE_DIR is the project directory of the project.

2022-10-06 09:04 UTC, davidmarogy commented on django_postgres_backup/common.py
> +BACKUP_PATH = BASE_DIR / "backup"
Renamed to DEFAULT_BACKUP_PATH

2022-10-06 09:05 UTC, davidmarogy commented on django_postgres_backup/common.py
> +def backup_file(
Done

2022-10-06 09:12 UTC, davidmarogy commented on django_postgres_backup/common.py
> +    additional_commands = ""
Done

2022-10-06 09:14 UTC, davidmarogy commented on django_postgres_backup/management/commands/postgres_backup.py
> +        parser.add_argument(
Renamed to BACKUP_DIR

2022-10-06 09:17 UTC, davidmarogy commented on django_postgres_backup/management/commands/postgres_backup.py
> +        run(["mkdir", "-p", "backup"])
Done

2022-10-06 09:19 UTC, davidmarogy commented on django_postgres_backup/management/commands/postgres_backup.py
> +        run(["mkdir", "-p", "backup"])
True, changed to path.

2022-10-06 09:22 UTC, davidmarogy commented on django_postgres_backup/management/commands/postgres_restore.py
> +    help = "Download bootstrap, build template css and copy bootstrap.bundle.min.js"
Done

2022-10-06 09:22 UTC, davidmarogy commented on django_postgres_backup/management/commands/postgres_backup.py
> +    help = "Download bootstrap, build template css and copy bootstrap.bundle.min.js"
Done

2022-10-06 11:19 UTC, davidmarogy commented on django_postgres_backup/management/commands/postgres_backup.py
> +        parser.add_argument("--file", "-f", metavar="FILENAME", default=DATABASE_NAME)
Renamed to name.

2022-10-06 11:21 UTC, davidmarogy commented on django_postgres_backup/management/commands/postgres_backup.py
> +        parser.add_argument("--generation", "-g", metavar="GENERATION", default=POSTGRES_BACKUP_GENERATIONS, type=int)
Done

2022-10-06 11:27 UTC, davidmarogy commented on django_postgres_backup/management/commands/postgres_restore.py
> +    def add_arguments(self, parser):
Done

2022-10-06 11:28 UTC, davidmarogy commented on django_postgres_backup/tests/test_commands.py
> +TEST_CREATE_TABLE_CARS_SQL = "create table cars (id SERIAL PRIMARY KEY , name VARCHAR(255) NOT NULL);"
Done

2022-10-06 11:30 UTC, davidmarogy commented on docker-compose.yaml
> +      POSTGRES_PASSWORD: "hid_d3n."
Done

2022-10-06 11:30 UTC, davidmarogy commented on example_app/admin.py
> +# Register your models here.
Done

2022-10-06 11:31 UTC, davidmarogy commented on example_app/models.py
> +# Create your models here.
Done

2022-10-06 11:31 UTC, davidmarogy commented on example_app/views.py
> +# Create your views here.
Done

2022-10-06 11:38 UTC, davidmarogy commented on scripts/reset_local_database.sh
> +# TODO: After migrations are under version control, remove this.
Removed TODO

2022-10-06 11:38 UTC, davidmarogy commented on scripts/reset_local_database.sh
> +# TODO: python manage.py makedemo
Removed TODO

2022-10-06 12:23 UTC, davidmarogy commented on django_postgres_backup/management/commands/postgres_backup.py
> +        parser.add_argument("--format", "-fo", metavar="FORMAT", default=DEFAULT_DATABASE_BACKUP_FORMAT)
Done

2022-10-10 07:32 UTC, davidmarogy commented on README.md
> +
Done

2022-10-10 08:55 UTC, davidmarogy commented on django_postgres_backup/common.py
> +        command = f"{sudo_command} bzip2 -d -c {file} -k | {command}"
Removed shell usage, therefore shlex is not needed.

2022-10-10 08:55 UTC, davidmarogy commented on django_postgres_backup/common.py
> +        command = f"{sudo_command} {command} {file}"
Removed shell usage, therefore shlex is not needed.

2022-10-11 09:03 UTC, roskakori requested changes

2022-10-11 09:03 UTC, roskakori commented on django_postgres_backup/common.py
> +        f"--host={DATABASE_HOST}",
Split into 2 parameters for consitent escaping, e.g.
```python
"--host", DATABASE_HOST,
```

2022-10-11 09:03 UTC, roskakori commented on django_postgres_backup/common.py
> +    with NamedTemporaryFile() as tmp_file:
Improve naming, e.g. `database_dump_file`

2022-10-11 09:03 UTC, roskakori commented on django_postgres_backup/common.py
> +    capture_output = False if output_file else True
Clearer:
```pyhon
capture_output = output_file is None
```

2022-10-11 09:03 UTC, roskakori commented on django_postgres_backup/management/commands/postgres_backup.py
> +        parser.add_argument("--username", "-u", metavar="USERNAME", default=DATABASE_USER, help="database username")
Sort options -> b, f, g, n, ...

2022-10-11 09:03 UTC, roskakori commented on django_postgres_backup/management/commands/postgres_backup.py
> +            help="maximum number of backups to be kept saved",
Add default:
```python
help="maximum number of backups to be kept saved, default: %(default)d",
```

2022-10-11 09:03 UTC, roskakori commented on django_postgres_backup/management/commands/postgres_backup.py
> +            help="directory where the backups are stored",
Add default

2022-10-11 09:03 UTC, roskakori commented on django_postgres_backup/management/commands/postgres_backup.py
> +            "-fo",
Use a single letter. Maybe:
--format, -f and --output, -o (instead if --file)

2022-10-11 09:03 UTC, roskakori commented on django_postgres_backup/management/commands/postgres_backup.py
> +    help = "Generates a backup for Postgresql and handles backup generations."
Use imperative, avoid dot: "Backup PostgreSQL database with multiple generations"

2022-10-11 09:03 UTC, roskakori commented on django_postgres_backup/management/commands/postgres_restore.py
> +    help = "Restore a backup for Postgresql."
PostgreSQL

2022-10-11 09:03 UTC, roskakori commented on django_postgres_backup/management/commands/postgres_restore.py
> +            help="directory where the backups are stored",
Add default

2022-10-11 09:03 UTC, roskakori commented on django_postgres_backup/management/commands/postgres_restore.py
>              help="use IF EXISTS when objects are deleted",
help="remove possibly existing database objects before restoring them"

2022-10-11 09:03 UTC, roskakori commented on example_app/models.py
>  class Cars(models.Model):
sigular: `Car`

2022-10-11 09:03 UTC, roskakori commented on example_app/views.py
> -# Create your views here.
Consider removing the entire file instead of leaving it empty.

2022-10-13 06:06 UTC, davidmarogy commented on django_postgres_backup/common.py
> +    with NamedTemporaryFile() as tmp_file:
Done

2022-10-13 06:07 UTC, davidmarogy commented on django_postgres_backup/common.py
> +    capture_output = False if output_file else True
done

2022-10-13 06:10 UTC, davidmarogy commented on django_postgres_backup/management/commands/postgres_backup.py
> +        parser.add_argument("--username", "-u", metavar="USERNAME", default=DATABASE_USER, help="database username")
done

2022-10-13 06:10 UTC, davidmarogy commented on django_postgres_backup/management/commands/postgres_backup.py
> +            help="maximum number of backups to be kept saved",
done

2022-10-13 06:11 UTC, davidmarogy commented on django_postgres_backup/management/commands/postgres_backup.py
> +            help="directory where the backups are stored",
done

2022-10-13 06:12 UTC, davidmarogy commented on django_postgres_backup/management/commands/postgres_backup.py
> +            "-fo",
done

2022-10-13 06:13 UTC, davidmarogy commented on django_postgres_backup/management/commands/postgres_backup.py
> +    help = "Generates a backup for Postgresql and handles backup generations."
done

2022-10-13 06:13 UTC, davidmarogy commented on django_postgres_backup/management/commands/postgres_restore.py
> +    help = "Restore a backup for Postgresql."
done

2022-10-13 06:15 UTC, davidmarogy commented on django_postgres_backup/management/commands/postgres_restore.py
> +            help="directory where the backups are stored",
done

2022-10-13 06:15 UTC, davidmarogy commented on django_postgres_backup/management/commands/postgres_restore.py
>              help="use IF EXISTS when objects are deleted",
done

2022-10-13 06:17 UTC, davidmarogy commented on example_app/models.py
>  class Cars(models.Model):
Done

2022-10-13 06:18 UTC, davidmarogy commented on example_app/views.py
> -# Create your views here.
done

2022-10-13 07:52 UTC, davidmarogy commented on django_postgres_backup/common.py
> +        f"--host={DATABASE_HOST}",
done

2022-10-14 07:20 UTC, roskakori approved these changes

2022-10-18 07:25 UTC, merged